accounting_double_entry/urls.py
from django.conf.urls import url
from accounting_double_entry import views

app_name = 'accounting_double_entry'

urlpatterns = [

####### Groups Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/grouplist/$',views.group1ListView.as_view(),name='grouplist'),    
    url(r'^company/(?P<pk1>\d+)/groupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1DetailView.as_view(),name='groupdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupcreate/$',views.group1CreateView.as_view(),name='groupcreate'),
    url(r'^company/(?P<pk1>\d+)/groupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1UpdateView.as_view(),name='groupupdate'),
    url(r'^company/(?P<pk>\d+)/groupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group_delete_view,name='groupdelete'),

####### Group Summary Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupsummary/$',views.groupsummaryListView.as_view(),name='groupsummary'),    
    url(r'^company/(?P<pk>\d+)/groupdetailsummary/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.groupsummary_detail_view,name='groupdetailsummary'),


####### Ledger Monthly Url ########################################

    url(r'^company/(?P<pk>\d+)/ledgermonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger_monthly_detail_view,name='ledgerdetailmonthly'),

####### Ledger Urls ########################################


    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerlist/$',views.ledger1ListView.as_view(),name='ledgerlist'),
    url(r'^company/(?P<pk>\d+)/ledgerdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger1_detail_view,name='ledgerdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgercreate/$',views.ledger1CreateView.as_view(),name='ledgercreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerupdate/(?P<pk2>\d+)/$',views.ledger1UpdateView.as_view(),name='ledgerupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerdelete/(?P<pk2>\d+)/$',views.ledger_delete_view,name='ledgerdelete'),

####### Journal Register Urls ########################################  

     url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journalregister/$',views.Journal_Register_view.as_view(),name='journalregister'),

####### Journal Urls ########################################  

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journallist/$',views.journalListView.as_view(),name='list'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journallist/(?P<pk2>\d+)/$',views.journal_detail,name='detail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/create/$',views.journalCreateView.as_view(),name='create'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journal/update/(?P<pk2>\d+)/$',views.journalUpdateView.as_view(),name='update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/delete/(?P<pk2>\d+)/$',views.journal_delete_view,name='delete'),


####### PL JOURNAL Urls ######################################## 

    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journallist/(?P<pk2>\d+)/$',views.pl_journal_detail,name='pl_detail'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journal/update/(?P<pk2>\d+)/$',views.pl_journalUpdateView.as_view(),name='pl_update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/pl_journal/delete/(?P<pk2>\d+)/$',views.pl_journal_delete_view,name='pl_delete'),

####### Multijournal Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/$',views.Multijournal_listview.as_view(),name='multijournallist'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/(?P<pk2>\d+)/$',views.multijournal_detail,name='multijournaldetail'),   
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/create/$',views.Multijournal_createview.as_view(),name='multijournalcreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournalupdate/(?P<pk2>\d+)/$',views.Multijournal_updateview.as_view(),name='multijournalupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/delete/(?P<pk2>\d+)/$',views.multijournal_deleteview.as_view(),name='multijournaldelete'),


####### Daterange Urls ########################################  
  
    url(r'^daterangecreate/$',views.selectdate_create,name='datecreate'),
    url(r'^daterangeupdate/(?P<pk>\d+)/$',views.selectdate_update,name='dateupdate'),

####### Payment Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/payment/create/$',views.Payment_createview.as_view(),name='paymentcreate'),

####### Receipt Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/receipt/create/$',views.Receipt_createview.as_view(),name='receiptcreate'),

####### Contra Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/contra/create/$',views.Contra_createview.as_view(),name='contracreate'),

####### Daybook Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/daybook/$',views.DaybookListView.as_view(),name='daybook'),




    url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_condensed_view,name='trialbalcond'),

    url(r'^company/(?P<pk>\d+)/P&L/date/(?P<pk3>\d+)/$',views.profit_and_loss_condensed_view,name='P&Lcond'),

    url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_condensed_view,name='blsht'),


    url(r'^company/(?P<pk>\d+)/cashbankbook/date/(?P<pk3>\d+)/$',views.cash_and_bank_view,name='cash_and_bank'),


]

cfehome/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.conf import settings

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^base/$", views.base.as_view(), name="base"),
    path('admin/', admin.site.urls),
    url(r"^message/", include("messaging.urls", namespace="messaging")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r"^products/", include("ecommerce_integration.urls", namespace="products")),
    url(r"^carts/", include("ecommerce_cart.urls", namespace="carts")),
    url(r"^accounting_double_entry/", include("accounting_double_entry.urls", namespace="accounting_double_entry")),
    url(r"^company/", include("company.urls", namespace="company")),
    url(r"^todo/", include("todogst.urls", namespace="todogst")),
    url(r"^profile/", include("userprofile.urls", namespace="userprofile")),
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r"^pdf/", include("pdf.urls", namespace="pdf")),
    # url(r"^gst/", include("Gst.urls", namespace="gst")),
    url(r'^select2/', include('django_select2.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r"^consultancy/", include("consultancy.urls", namespace="consultancy")),
    url(r"^stockkeeping/", include("stockkeeping.urls", namespace="stockkeeping")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'erpcloud.views.custom_404'
handler500 = 'erpcloud.views.custom_500'

pdf/urls.py
from django.conf.urls import url
from pdf import views

app_name = 'pdf'

urlpatterns = [

########################################### PDF URLS ############################################################################################################################
	url(r'^company/(?P<pk1>\d+)/purchasedetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Purchase_PDF.as_view(),name='purchasedetailpdf'),
	url(r'^company/(?P<pk1>\d+)/saledetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Sales_PDF.as_view(),name='salesdetailpdf'),
    url(r'^company/(?P<pk>\d+)/ledgermonthlypdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Ledger_Monthly_PDF.as_view(),name='ledgerdetailmonthlypdf'),


]

stockkeeping/urls.py
from django.conf.urls import url
from stockkeeping import views

app_name = 'stockkeeping'

urlpatterns = [


################################### Simple Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitlist$',views.Simpleunits_listview.as_view(),name='simplelist'),
	url(r'^company/(?P<pk1>\d+)/simpleunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_detailsview.as_view(),name='simpledetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitcreate/$',views.Simpleunits_createview.as_view(),name='simplecreate'),
	url(r'^company/(?P<pk1>\d+)/simpleunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_updateview.as_view(),name='simpleupdate'),
	url(r'^company/(?P<pk>\d+)/simpleunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_deleteview.as_view(),name='simpledelete'),

################################### Compound Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitlist$',views.Compoundunit_listview.as_view(),name='compoundlist'),
	url(r'^company/(?P<pk1>\d+)/compoundunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_detailsview.as_view(),name='compounddetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitcreate/$',views.Compoundunits_createview.as_view(),name='compoundcreate'),
	url(r'^company/(?P<pk1>\d+)/compoundunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_updateview.as_view(),name='compoundupdate'),
	url(r'^company/(?P<pk>\d+)/compoundunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_deleteview.as_view(),name='compounddelete'),

################################### Stockgroup Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgrouplist$',views.Stockgroup_listview.as_view(),name='stockgrouplist'),
	url(r'^company/(?P<pk1>\d+)/stockgroupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_detailsview.as_view(),name='stockgroupdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgroupcreate/$',views.Stockgroup_createview.as_view(),name='stockgroupcreate'),
	url(r'^company/(?P<pk1>\d+)/stockgroupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_updateview.as_view(),name='stockgroupupdate'),
	url(r'^company/(?P<pk>\d+)/stockgroupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_deleteview.as_view(),name='stockgroupdelete'),


################################### Stockdata Monthly Url ######################################

    url(r'^company/(?P<pk>\d+)/stockmonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockitems_Monthly_view,name='stockmonthly'),


################################### Stockdata Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdata$',views.Stockdata_listview.as_view(),name='stockdatalist'),
	url(r'^company/(?P<pk1>\d+)/stockdatadetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_detailsview.as_view(),name='stockdatadetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdatacreate/$',views.Stockdata_createview.as_view(),name='stockdatacreate'),
	url(r'^company/(?P<pk1>\d+)/stockdataupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_updateview.as_view(),name='stockdataupdate'),
	url(r'^company/(?P<pk>\d+)/stockdatadelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_deleteview.as_view(),name='stockdatadelete'),

################################### Purchase Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchase$',views.Purchase_listview.as_view(),name='purchaselist'),
	url(r'^company/(?P<pk1>\d+)/purchasedetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_detailsview.as_view(),name='purchasedetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchasecreate/$',views.Purchase_createview.as_view(),name='purchasecreate'),
	url(r'^company/(?P<pk1>\d+)/purchaseupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_updateview.as_view(),name='purchaseupdate'),
	url(r'^company/(?P<pk>\d+)/purchasedelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_deleteview.as_view(),name='purchasedelete'),


################################### Purchase Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Purchase_Register/date/(?P<pk3>\d+)/$',views.Purchase_Register_view.as_view(),name='purchase_register'),



################################### Sale Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Sale_Register/date/(?P<pk3>\d+)/$',views.Sales_Register_view.as_view(),name='sale_register'),

################################### Sales Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/sales$',views.Sales_listview.as_view(),name='saleslist'),
	url(r'^company/(?P<pk1>\d+)/salesdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_detailsview.as_view(),name='salesdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/salescreate/$',views.Sales_createview.as_view(),name='salescreate'),
	url(r'^company/(?P<pk1>\d+)/salesupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_updateview.as_view(),name='salesupdate'),
	url(r'^company/(?P<pk>\d+)/salesdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_deleteview.as_view(),name='salesdelete'),


	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stcreate/$',views.Stock_Total_createview.as_view(),name='stocktotalcreate'),


################################### Closing Stock Url #######################################
	
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.closing_list_view.as_view(),name='closingstock'),


################################### Profit & Loss Url #######################################

    url(r'^company/(?P<pk>\d+)/Profitloss/date/(?P<pk3>\d+)/$',views.profit_and_loss_view,name='profitloss'),

################################### Trial Balance Url #######################################

	url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_view,name='trialbal'),

################################### Balance Sheet Url #######################################

	
	url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_view,name='balsht'),

]

accounting_double_entry/templates/accounting_double_entry/group1_list2.html
{% for group in group1_list %}
  <tr>

    <td><center><a href="{% url 'accounting_double_entry:groupdetail' pk1=company_details.pk pk2=group.pk pk3=selectdatefield_details.pk %}">{{group.group_Name}}</a></center></td>


    <td><a href="{% url 'accounting_double_entry:groupdetail' pk1=company_details.pk pk2=group.pk pk3=selectdatefield_details.pk %}">{{group.counter}}</a></td>

    <td><a href="{% url 'accounting_double_entry:groupdetail' pk1=company_details.pk pk2=group.pk pk3=selectdatefield_details.pk %}">{{group.Master}}</a></td>

    <td><a href="{% url 'accounting_double_entry:groupdetail' pk1=company_details.pk pk2=group.pk pk3=selectdatefield_details.pk %}">{{group.balance_nature}}</a></td>

    <td>
    <center>
       <button class="btn btn-danger show-form-delete" data-url="{% url 'accounting_double_entry:groupdelete' pk=company_details.pk pk2=group.pk pk3=selectdatefield_details.pk %}">
        <span class="glyphicon glyphicon-trash"></span>
                              
    </button> 
    </center>
    
    </td>

  </tr>

{% endfor %}

accounting_double_entry/templates/accounting_double_entry/ledger_monthly.html
{% extends "clouderp/base.html" %}
{% load staticfiles %}
{% load mathfilters %}

{% block title %}Ledger List View{% endblock %}




{% block content %}

<div class="content-wrapper">
   <section class="content-header">
        <!-- <div class="col-md-12 col-md-offset-4"> -->
          <h1>
            <strong>Company : {{company_details.Name}}</strong>
          </h1>
                <ol class="breadcrumb">
                       <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                       <!-- <li><a href="#">Company list</a></li> -->
                     <li class="">Company list</li>
                     <li class="active">Group Details</li>
            </ol>
           
        <!-- </div> -->
      </section>

  <section class="content">
      <div class="callout callout-warning">
        <h4>Welcome!</h4>
        Welcome to predict books your personal AI powered business engine!
        <!-- <a href="http://getbootstrap.com/javascript/#modals">Bootstrap documentation</a> -->
      </div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

      <a href="{% url 'company:list' %}" class="btn btn-success" role="button">Select Company </a>
              <a href="{% url 'company:create' %}" class="btn btn-warning" role="button">Create Company details</a>
              

        
        
              {% if not selectdatefield_details %}

                  
                     <button class="btn btn-primary show-form pull-right" data-url="{% url 'accounting_double_entry:datecreate' %}">
                      <span class="glyphicon glyphicon-plus"></span>
                        Select Date Range
                      </button>

                {% else %} 
              
  
                            <button  class="btn btn-warning show-form-update pull-right" data-url="{% url 'accounting_double_entry:dateupdate' pk=selectdatefield_details.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                              Update Date Range 
                            </button>

                      <a id="book-table-date" class="pull-right"><strong>Selected Period: From</strong> {{ selectdatefield_details.Start_Date|date }} <strong>To</strong> {{ selectdatefield_details.End_Date|date }}  &nbsp;</a>  

                 

                {% endif %}
        
        </div>
      
      </div>
    
    </div>

</div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

         <a href="{% url 'accounting_double_entry:ledgerlist' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-success" role="button">Select Ledger </a>
                <a href="{% url 'accounting_double_entry:ledgercreate' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-warning" role="button">Create Ledger</a>

                <a href="{% url 'accounting_double_entry:ledgerdetail' pk=company_details.pk pk2=ledger1_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-primary" role="button">T view</a>

                <div class="pull-right">
                  <a href="{% url 'accounting_double_entry:create' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-warning" role="button">Create Journal</a>
                </div>


        
        
        </div>
      
      </div>
    
    </div>

</div>


  

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="box box-info">


  <div id="printableArea">

      <!--         CSS for not printing the urls in print preview
 -->      <style>
          @media print  
          {
          a[href]:after {
          content: none !important;
           }
          @page {
          margin-top: 0;
          margin-bottom: 0;
          }
           body{
          padding-top: 72px;
          padding-bottom: 72px ;
          }
          }
          </style>
    
    <div class="box-header with-border">
              
              <h3 class="box-title"><b>Ledger Details</b></h3>
        
          </div>

          <div class="box-header with-border">
              
              <h2><b><center>{{ ledger1_details.name }}</center></b></h2>
        
          </div>

          <div class="box-body table-responsive no-padding">

          <style type="text/css">

          .table-bordered td, .table-bordered th{
            border-color: #bfbfbf !important;
                    
               }
        </style>

            <table class="table table-bordered table-striped">

              
                 <tr>
                  <th><center>Months</center></th>
                  <th><center>Debit(&#8377)</center></th>
                  <th><center>Credit(&#8377)</center></th>
                  <th><center>Closing Balance(&#8377)</center></th>
                </tr>
              


                <tr>
                  <th><center>Opening Balance</center></th>
                  <th><center></center></th>
                  <th><center></center></th>
                  {% if ledger1_details.group1_Name.balance_nature == 'Debit' %}

                    {% if opening_balance > 0 %}

                      {% if opening_balance == 0 %}

                        <th><center></center></th>

                      {% else %}

                        <th><center>{{ opening_balance }} Dr</center></th>

                      {% endif %}
                      

                    {% else %}

                      {% if opening_balance == 0 %}

                        <th><center></center></th>

                      {% else %}

                        <th><center>{{ opening_balance }} Cr</center></th>
                      {% endif %}

                    {% endif %}

                  {% else %}


                    {% if opening_balance > 0 %}

                      {% if opening_balance == 0 %}

                        <th><center></center></th>

                      {% else %}

                        <th><center>{{ opening_balance }} Cr</center></th>

                      {% endif %}

                    {% else %}

                      {% if opening_balance == 0 %}

                        <th><center></center></th>

                      {% else %}

                        <th><center>{{ opening_balance }} Dr</center></th>
                        
                      {% endif %}

                    {% endif %}

                  {% endif %}
                </tr>               
                

                {% for key, value in data %}
                  <tr>
                    <td><center>{{ key }}</center></td>

                    {% if value.3 != 0 and value.0 == 0 %}
                      <td><center>{{ value.3 }}</center></td>
                    {% elif value.0 != 0 and value.3 == 0 %}
                      <td><center>{{ value.0 }}</center></td>
                    {% elif value.0 == 0 and value.3 == 0 %}
                      <td><center></center></td> 
                    {% else %}
                      <td><center>{{ value.0|add:value.3 }}</center></td>
                    {% endif %}



                    {% if value.4 != 0 and value.1 == 0 %}
                      <td><center>{{ value.4 }}</center></td>
                    {% elif value.1 != 0 and value.4 == 0 %}
                      <td><center>{{ value.1 }}</center></td>
                    {% elif value.1 == 0 and value.4 == 0 %}
                      <td><center></center></td> 
                    {% else %}
                      <td><center>{{ value.1|add:value.4 }}</center></td>
                    {% endif %}

                  {% if ledger1_details.group1_Name.balance_nature == 'Debit' %}

                    {% if value.2 > 0 %}


                          <td><center>{{ value.2|abs }} Dr</center></td>
                        

                    {% else %}


                          <td><center>{{ value.2|abs }} Cr</center></td>
                        

                    {% endif %}
                      </tr>

                  {% else %}
                    
                      {% if value.2 > 0 %}


                          <td><center>{{ value.2|abs }} Cr</center></td>
                        

                      {% else %}


                          <td><center>{{ value.2|abs }} Dr</center></td>
                       

                      {% endif %}
                  {% endif %}

                      </tr>
                {% endfor %}

                  <tr>
                    <th><center></center></th>
                    <th><center></center></th>
                    <th><center></center></th>
                    <th><center></center></th>
                  </tr>

                <tr>
                  <th><center>Grand Total</center></th>

                  {% if total_debit == 0 and total_debit_pl == 0 %}
                    <th><center></center></th>
                  {% else %}
                    <th><center>{{ total_debit|add:total_debit_pl }}</center></th>
                  {% endif %}

                  {% if total_credit == 0 and total_credit_pl == 0 %}
                    <th><center></center></th>
                  {% else %}
                    <th><center>{{ total_credit|add:total_credit_pl }}</center></th>
                  {% endif %}
                  
               

                  {% if ledger1_details.group1_Name.balance_nature == 'Debit' %}

                    {% if total > 0 %}
                      <th><center>{{ total|abs }} Dr</center></th>

                    {% else %}

                      <th><center>{{ total|abs }} Cr</center></th>

                    {% endif %}

                  {% else %}

                    {% if total > 0 %}
                      <th><center>{{ total|abs }} Cr</center></th>

                    {% else %}

                      <th><center>{{ total|abs }} Dr</center></th>

                    {% endif %}

                  {% endif %} 
                    
                </tr>                
                



            </table>
          </div>

  </div>

          



                            <div class="box-footer">
                    <hr>
                     <div class="pull-left">
                     <input class='btn btn-default' type="button" onclick="printDiv('printableArea')" value="Print" />
                    
                     </div>

                  <div class="pull-right">
                    <a href="{% url 'pdf:ledgerdetailmonthlypdf' pk=company_details.pk pk2=ledger1_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-primary pull-right" role="button"><i class="fa fa-download"></i>Generate PDF</a>



                  </div>

        </div>


        </div>
      </div>
    
  </section>
</div>




  <div class="modal fade" id="modal-book-date">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>
  

<script type="text/javascript">
  
  function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;

     window.print();

     document.body.innerHTML = originalContents;
  }
</script>

{% endblock %}