accounting_double_entry/urls.py
from django.conf.urls import url
from accounting_double_entry import views

app_name = 'accounting_double_entry'

urlpatterns = [

####### Groups Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/grouplist/$',views.group1ListView.as_view(),name='grouplist'),    
    url(r'^company/(?P<pk1>\d+)/groupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1DetailView.as_view(),name='groupdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupcreate/$',views.group1CreateView.as_view(),name='groupcreate'),
    url(r'^company/(?P<pk1>\d+)/groupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1UpdateView.as_view(),name='groupupdate'),
    url(r'^company/(?P<pk>\d+)/groupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group_delete_view,name='groupdelete'),

####### Group Summary Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupsummary/$',views.groupsummaryListView.as_view(),name='groupsummary'),    
    url(r'^company/(?P<pk>\d+)/groupdetailsummary/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.groupsummary_detail_view,name='groupdetailsummary'),


####### Ledger Monthly Url ########################################

    url(r'^company/(?P<pk>\d+)/ledgermonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger_monthly_detail_view,name='ledgerdetailmonthly'),

####### Ledger Urls ########################################


    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerlist/$',views.ledger1ListView.as_view(),name='ledgerlist'),
    url(r'^company/(?P<pk>\d+)/ledgerdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger1_detail_view,name='ledgerdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgercreate/$',views.ledger1CreateView.as_view(),name='ledgercreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerupdate/(?P<pk2>\d+)/$',views.ledger1UpdateView.as_view(),name='ledgerupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerdelete/(?P<pk2>\d+)/$',views.ledger_delete_view,name='ledgerdelete'),

####### Journal Register Urls ########################################  

     url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journalregister/$',views.Journal_Register_view.as_view(),name='journalregister'),

####### Journal Urls ########################################  

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journallist/$',views.journalListView.as_view(),name='list'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journallist/(?P<pk2>\d+)/$',views.journal_detail,name='detail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/create/$',views.journalCreateView.as_view(),name='create'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journal/update/(?P<pk2>\d+)/$',views.journalUpdateView.as_view(),name='update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/delete/(?P<pk2>\d+)/$',views.journal_delete_view,name='delete'),


####### PL JOURNAL Urls ######################################## 

    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journallist/(?P<pk2>\d+)/$',views.pl_journal_detail,name='pl_detail'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journal/update/(?P<pk2>\d+)/$',views.pl_journalUpdateView.as_view(),name='pl_update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/pl_journal/delete/(?P<pk2>\d+)/$',views.pl_journal_delete_view,name='pl_delete'),

####### Multijournal Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/$',views.Multijournal_listview.as_view(),name='multijournallist'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/(?P<pk2>\d+)/$',views.multijournal_detail,name='multijournaldetail'),   
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/create/$',views.Multijournal_createview.as_view(),name='multijournalcreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournalupdate/(?P<pk2>\d+)/$',views.Multijournal_updateview.as_view(),name='multijournalupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/delete/(?P<pk2>\d+)/$',views.multijournal_deleteview.as_view(),name='multijournaldelete'),


####### Daterange Urls ########################################  
  
    url(r'^daterangecreate/$',views.selectdate_create,name='datecreate'),
    url(r'^daterangeupdate/(?P<pk>\d+)/$',views.selectdate_update,name='dateupdate'),

####### Payment Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/payment/create/$',views.Payment_createview.as_view(),name='paymentcreate'),

####### Receipt Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/receipt/create/$',views.Receipt_createview.as_view(),name='receiptcreate'),

####### Contra Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/contra/create/$',views.Contra_createview.as_view(),name='contracreate'),

####### Daybook Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/daybook/$',views.DaybookListView.as_view(),name='daybook'),




    url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_condensed_view,name='trialbalcond'),

    url(r'^company/(?P<pk>\d+)/P&L/date/(?P<pk3>\d+)/$',views.profit_and_loss_condensed_view,name='P&Lcond'),

    url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_condensed_view,name='blsht'),


    url(r'^company/(?P<pk>\d+)/cashbankbook/date/(?P<pk3>\d+)/$',views.cash_and_bank_view,name='cash_and_bank'),


]

company/urls.py
from django.conf.urls import url,include
from company import views
from django.urls import path

app_name = 'company'

urlpatterns = [
######################### Company Urls ################################################
    url(r'^$',views.companyListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.companyDetailView.as_view(),name='Dashboard'),
    url(r'^create/$',views.companyCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.companyUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<id>\d+)/$',views.company_delete,name='delete'),
	
]

pdf/urls.py
from django.conf.urls import url
from pdf import views

app_name = 'pdf'

urlpatterns = [

########################################### PDF URLS ############################################################################################################################
	url(r'^company/(?P<pk1>\d+)/purchasedetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Purchase_PDF.as_view(),name='purchasedetailpdf'),
	url(r'^company/(?P<pk1>\d+)/saledetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Sales_PDF.as_view(),name='salesdetailpdf'),
    url(r'^company/(?P<pk>\d+)/ledgermonthlypdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Ledger_Monthly_PDF.as_view(),name='ledgerdetailmonthlypdf'),


]

stockkeeping/urls.py
from django.conf.urls import url
from stockkeeping import views

app_name = 'stockkeeping'

urlpatterns = [


################################### Simple Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitlist$',views.Simpleunits_listview.as_view(),name='simplelist'),
	url(r'^company/(?P<pk1>\d+)/simpleunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_detailsview.as_view(),name='simpledetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitcreate/$',views.Simpleunits_createview.as_view(),name='simplecreate'),
	url(r'^company/(?P<pk1>\d+)/simpleunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_updateview.as_view(),name='simpleupdate'),
	url(r'^company/(?P<pk>\d+)/simpleunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_deleteview.as_view(),name='simpledelete'),

################################### Compound Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitlist$',views.Compoundunit_listview.as_view(),name='compoundlist'),
	url(r'^company/(?P<pk1>\d+)/compoundunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_detailsview.as_view(),name='compounddetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitcreate/$',views.Compoundunits_createview.as_view(),name='compoundcreate'),
	url(r'^company/(?P<pk1>\d+)/compoundunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_updateview.as_view(),name='compoundupdate'),
	url(r'^company/(?P<pk>\d+)/compoundunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_deleteview.as_view(),name='compounddelete'),

################################### Stockgroup Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgrouplist$',views.Stockgroup_listview.as_view(),name='stockgrouplist'),
	url(r'^company/(?P<pk1>\d+)/stockgroupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_detailsview.as_view(),name='stockgroupdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgroupcreate/$',views.Stockgroup_createview.as_view(),name='stockgroupcreate'),
	url(r'^company/(?P<pk1>\d+)/stockgroupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_updateview.as_view(),name='stockgroupupdate'),
	url(r'^company/(?P<pk>\d+)/stockgroupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_deleteview.as_view(),name='stockgroupdelete'),


################################### Stockdata Monthly Url ######################################

    url(r'^company/(?P<pk>\d+)/stockmonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockitems_Monthly_view,name='stockmonthly'),


################################### Stockdata Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdata$',views.Stockdata_listview.as_view(),name='stockdatalist'),
	url(r'^company/(?P<pk1>\d+)/stockdatadetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_detailsview.as_view(),name='stockdatadetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdatacreate/$',views.Stockdata_createview.as_view(),name='stockdatacreate'),
	url(r'^company/(?P<pk1>\d+)/stockdataupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_updateview.as_view(),name='stockdataupdate'),
	url(r'^company/(?P<pk>\d+)/stockdatadelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_deleteview.as_view(),name='stockdatadelete'),

################################### Purchase Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchase$',views.Purchase_listview.as_view(),name='purchaselist'),
	url(r'^company/(?P<pk1>\d+)/purchasedetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_detailsview.as_view(),name='purchasedetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchasecreate/$',views.Purchase_createview.as_view(),name='purchasecreate'),
	url(r'^company/(?P<pk1>\d+)/purchaseupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_updateview.as_view(),name='purchaseupdate'),
	url(r'^company/(?P<pk>\d+)/purchasedelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_deleteview.as_view(),name='purchasedelete'),


################################### Purchase Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Purchase_Register/date/(?P<pk3>\d+)/$',views.Purchase_Register_view.as_view(),name='purchase_register'),



################################### Sale Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Sale_Register/date/(?P<pk3>\d+)/$',views.Sales_Register_view.as_view(),name='sale_register'),

################################### Sales Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/sales$',views.Sales_listview.as_view(),name='saleslist'),
	url(r'^company/(?P<pk1>\d+)/salesdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_detailsview.as_view(),name='salesdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/salescreate/$',views.Sales_createview.as_view(),name='salescreate'),
	url(r'^company/(?P<pk1>\d+)/salesupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_updateview.as_view(),name='salesupdate'),
	url(r'^company/(?P<pk>\d+)/salesdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_deleteview.as_view(),name='salesdelete'),


	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stcreate/$',views.Stock_Total_createview.as_view(),name='stocktotalcreate'),


################################### Closing Stock Url #######################################
	
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.closing_list_view.as_view(),name='closingstock'),


################################### Profit & Loss Url #######################################

    url(r'^company/(?P<pk>\d+)/Profitloss/date/(?P<pk3>\d+)/$',views.profit_and_loss_view,name='profitloss'),

################################### Trial Balance Url #######################################

	url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_view,name='trialbal'),

################################### Balance Sheet Url #######################################

	
	url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_view,name='balsht'),

]

stockkeeping/templates/stockkeeping/sales/sales_confirm_delete.html
{% extends "clouderp/base.html" %}
{% load staticfiles %}

{% block title %}Delete Purchase Invoice{% endblock %}




{% block content %}

<div class="content-wrapper">
   <section class="content-header">
        <!-- <div class="col-md-12 col-md-offset-4"> -->
          <h1>
            <strong>Company : {{company_details.Name}}</strong>
          </h1>
                <ol class="breadcrumb">
                       <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                       <!-- <li><a href="#">Company list</a></li> -->
                     <li class="">Company list</li>
                     <li class="active">Group Details</li>
            </ol>
           
        <!-- </div> -->
      </section>

  <section class="content">
      <div class="callout callout-warning">
        <h4>Welcome!</h4>
        Welcome to predict books your personal AI powered business engine!
        <!-- <a href="http://getbootstrap.com/javascript/#modals">Bootstrap documentation</a> -->
      </div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

              <a href="{% url 'company:create' %}" class="btn btn-warning" role="button">Create Company details</a>
              

        
        
        
        </div>
      
      </div>
    
    </div>

</div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

           <a href="{% url 'stockkeeping:saleslist' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-success" role="button">Select Sales Invoice</a>
          
          <a href="{% url 'stockkeeping:salescreate' pk=company_details.pk pk3=selectdatefield_details.pk  %}" class="btn btn-warning" role="button">Create Sales Invoice</a>

        
        
        
        </div>
      
      </div>
    
    </div>

</div>


 
    <div class="box box-info">
          <div class="box-body">
              <div class="col-md-12">
              <h1>
              <strong>Delete {{sales.Name }}?</strong>
              </h1>
              </div>
          </div>
       
   
<div class="box-footer">
  <form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a class='btn btn-default' href="{% url 'stockkeeping:salesdetail' pk2=sales.pk pk1=company_details.pk pk3=selectdatefield_details.pk %}">Cancel</a>

</form>
</div>

</div>
  



    
  </section>
</div>

    
  
  

  

{% endblock %}

stockkeeping/templates/stockkeeping/sales/sales_details.html
{% extends "clouderp/base.html" %}
{% load staticfiles %}
{% load mathfilters %}
{% load humanize %}

{% block title %}
  
    Sales Invoice
   
{% endblock %}

{% block content %}

<div class="content-wrapper">
<!-- <div class="container"> -->
      <section class="content-header">
        <!-- <div class="col-md-12 col-md-offset-4"> -->
          <h1>
            <strong>Company : {{company_details.Name}}</strong>
          </h1>
                <ol class="breadcrumb">
                       <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                       <!-- <li><a href="#">Company list</a></li> -->
                     <li class="">Company list</li>
                     <li class="active">Create Simple Unit</li>
            </ol>
        <!-- </div> -->
      </section>

  <section class="content">
      <div class="callout callout-warning">
        <h4>Welcome!</h4>
        Welcome to predict books your personal AI powered business engine!
        <!-- <a href="http://getbootstrap.com/javascript/#modals">Bootstrap documentation</a> -->
      </div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

      <a href="{% url 'company:list' %}" class="btn btn-success" role="button">Select Company </a>
              <a href="{% url 'company:create' %}" class="btn btn-warning" role="button">Create Company details</a>
            

        
              {% if not selectdatefield_details %}

                  
                     <button class="btn btn-primary show-form pull-right" data-url="{% url 'accounting_double_entry:datecreate' %}">
                      <span class="glyphicon glyphicon-plus"></span>
                        Select Date Range
                      </button>

                {% else %} 
              
  
                            <button  class="btn btn-warning show-form-update pull-right" data-url="{% url 'accounting_double_entry:dateupdate' pk=selectdatefield_details.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                              Update Date Range 
                            </button>

                      <a id="book-table-date" class="pull-right"><strong>Selected Period: From</strong> {{ selectdatefield_details.Start_Date|date }} <strong>To</strong> {{ selectdatefield_details.End_Date|date }}  &nbsp;</a>  

                 

                {% endif %} 
        
        </div>
      
      </div>
    
    </div>

</div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

        <a href="{% url 'stockkeeping:saleslist' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-success" role="button">Select Sales Invoice</a>
          
          <a href="{% url 'stockkeeping:salescreate' pk=company_details.pk pk3=selectdatefield_details.pk  %}" class="btn btn-warning" role="button">Create Sales Invoice</a>
                  
        </div>
      
      </div>
    
    </div>

</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <!-- Horizontal Form -->
          <div class="box box-info">

<div id="printableArea">
  
              <div class="box-header with-border">
            
              <h3 class="box-title"> Sales Invoice</h3>
           
            </div>
            <!-- /.box-header -->
  <div class="box-body">
     <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <i class="fa fa-globe"></i> {{company_details.Name}}
            <small class="pull-right">Date: {{sales_details.date}}</small>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">

        
        <div class="col-sm-4 invoice-col">
         Seller
          <address>
            <strong>{{company_details.Name}}</strong><br>
            {{company_details.Address}}<br>
             Pin   : {{company_details.Pincode}}<br>
             State : {{company_details.State}}<br>
             Phone : {{company_details.Mobile_No}}<br>
             GSTIN : {{company_details.gst}}<br>
          </address>
        </div>

        <div class="col-sm-4 invoice-col">
        Buyer
          <address>
            <strong>{{sales_details.billname}}</strong><br>
            {{sales_details.Address}}<br>
            State : {{sales_details.State}}<br>
            Phone : {{sales_details.Contact}}<br>
            
          </address>
        </div>
        <!-- /.col -->
        
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Invoice #{{sales_details.ref_no}}</b><br>
          <br>
          <b>Order ID:</b> {{sales_details.id}}<br>
          <b>Payment Due:</b> ----<br>
          <b>Account:</b> ----
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Sl.no</th>
              <th>Product</th>
              <th>Quantity</th>
              <th>Rate</th>
              <th>Discount(%)</th>
              <th>Sub Total(&#8377;)</th>
              {% if company_details.State == sales_details.State %}
                <th>CGST(%)</th>
                <th>SGST(%)</th>
              {% else %}
                <th>IGST(%)</th>
              {% endif %}
              <th>Total(&#8377;)</th>
            </tr>
            </thead>
            <tbody>
            {% for stock_total in stocklist %}

              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{stock_total.stockitem}}</td>
                <td>{{stock_total.Quantity}}</td>
                <td>{{stock_total.rate}}</td>
                <td>{{stock_total.Disc}}</td>
                <td>{{stock_total.Total}}</td>
                {% if company_details.State == sales_details.State %}                

                  <td>{{stock_total.cgst_total|intcomma}}-({{stock_total.cgst}}%)</td>
                  <td>{{stock_total.gst_total|intcomma}}-({{stock_total.sgst}}%)</td>
                
                {% else %}

                  <td>{{stock_total.gst_total|intcomma}}-({{stock_total.igst}}%)</td>

                {% endif %}

                <td>{{stock_total.grand_total|intcomma}}</td>
                
              </tr>


              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
          <p class="lead"><strong>Company Bank Details:</strong></p>
          
          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            <strong>Bank Name:</strong>_____________________________________  
          </p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            <strong>A/c no:</strong>__________________________________________
          </p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            <strong>
            Branch & IFSC code:</strong>_______________________________  
          </p>
          <p class="lead"><strong>Declaration:</strong></p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            We declare that this invoice shows the actual price of the goods described and all the paritculars are true and correct.
          </p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            Subjected to local jurisdiction.
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          

          <div class="table-responsive">
            <table class="table">
              <tr>
                <th style="width:50%">Subtotal:(&#8377;)</th>
                <td>{{sales_details.sub_total|intcomma}}</td>
              </tr>
          {% if company_details.State == sales_details.State %}
              <tr>
                <th style="width:50%">CGST:(&#8377;)</th>
                <td>{{sales_details.cgst_alltotal|intcomma}}</td>
              </tr>
              <tr>
                <th style="width:50%">SGST:(&#8377;)</th>
                <td>{{sales_details.gst_alltotal|intcomma}}</td>
              </tr>
          {% else %}
              <tr>
                <th style="width:50%">IGST:(&#8377;)</th>
                <td>{{sales_details.gst_alltotal|intcomma}}</td>
              </tr>
          {% endif %}
              <tr>
                <th style="width:50%">Total:(&#8377;)</th>
                <td>{{sales_details.Total|intcomma}}</td>
              </tr>
            </table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
  </div>      <!-- form start -->
   


</div>
<!-- printablearea -->

      <!-- this row will not appear when printing -->
      <div class="box-footer">
        
          <input class='btn btn-default' type="button" onclick="printDiv('printableArea')" value="Print" />


         <!--  <form>
            <input type=button value="Print me!" onClick="javascript:window.print()">
        </form> -->

          <a class='btn btn-warning' href="{% url 'stockkeeping:salesupdate' pk1=company_details.pk pk2=sales_details.pk pk3=selectdatefield_details.pk %}">Update Sales Invoice</a><a class='btn btn-danger pull-right' href="{% url 'stockkeeping:salesdelete' pk=company_details.pk pk2=sales_details.pk pk3=selectdatefield_details.pk %}">Delete Sales Invoice</a>

          <a href="{% url 'pdf:salesdetailpdf' pk2=sales_details.pk pk1=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-primary pull-right" role="button"><i class="fa fa-download "></i> Generate Pdf</a>
       
      </div>
 
          </div>

        </div>
</div>








</section>
</div>

  <div class="modal fade" id="modal-book-date">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>

    
<script type="text/javascript">
  
  function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;

     window.print();

     document.body.innerHTML = originalContents;
  }
</script>   

{% endblock %}