accounting_double_entry/urls.py
from django.conf.urls import url
from accounting_double_entry import views

app_name = 'accounting_double_entry'

urlpatterns = [

####### Groups Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/grouplist/$',views.group1ListView.as_view(),name='grouplist'),    
    url(r'^company/(?P<pk1>\d+)/groupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1DetailView.as_view(),name='groupdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupcreate/$',views.group1CreateView.as_view(),name='groupcreate'),
    url(r'^company/(?P<pk1>\d+)/groupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1UpdateView.as_view(),name='groupupdate'),
    url(r'^company/(?P<pk>\d+)/groupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group_delete_view,name='groupdelete'),

####### Group Summary Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupsummary/$',views.groupsummaryListView.as_view(),name='groupsummary'),    
    url(r'^company/(?P<pk>\d+)/groupdetailsummary/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.groupsummary_detail_view,name='groupdetailsummary'),


####### Ledger Monthly Url ########################################

    url(r'^company/(?P<pk>\d+)/ledgermonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger_monthly_detail_view,name='ledgerdetailmonthly'),

####### Ledger Urls ########################################


    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerlist/$',views.ledger1ListView.as_view(),name='ledgerlist'),
    url(r'^company/(?P<pk>\d+)/ledgerdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger1_detail_view,name='ledgerdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgercreate/$',views.ledger1CreateView.as_view(),name='ledgercreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerupdate/(?P<pk2>\d+)/$',views.ledger1UpdateView.as_view(),name='ledgerupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerdelete/(?P<pk2>\d+)/$',views.ledger_delete_view,name='ledgerdelete'),

####### Journal Register Urls ########################################  

     url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journalregister/$',views.Journal_Register_view.as_view(),name='journalregister'),

####### Journal Urls ########################################  

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journallist/$',views.journalListView.as_view(),name='list'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journallist/(?P<pk2>\d+)/$',views.journal_detail,name='detail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/create/$',views.journalCreateView.as_view(),name='create'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journal/update/(?P<pk2>\d+)/$',views.journalUpdateView.as_view(),name='update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/delete/(?P<pk2>\d+)/$',views.journal_delete_view,name='delete'),


####### PL JOURNAL Urls ######################################## 

    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journallist/(?P<pk2>\d+)/$',views.pl_journal_detail,name='pl_detail'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journal/update/(?P<pk2>\d+)/$',views.pl_journalUpdateView.as_view(),name='pl_update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/pl_journal/delete/(?P<pk2>\d+)/$',views.pl_journal_delete_view,name='pl_delete'),

####### Multijournal Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/$',views.Multijournal_listview.as_view(),name='multijournallist'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/(?P<pk2>\d+)/$',views.multijournal_detail,name='multijournaldetail'),   
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/create/$',views.Multijournal_createview.as_view(),name='multijournalcreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournalupdate/(?P<pk2>\d+)/$',views.Multijournal_updateview.as_view(),name='multijournalupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/delete/(?P<pk2>\d+)/$',views.multijournal_deleteview.as_view(),name='multijournaldelete'),


####### Daterange Urls ########################################  
  
    url(r'^daterangecreate/$',views.selectdate_create,name='datecreate'),
    url(r'^daterangeupdate/(?P<pk>\d+)/$',views.selectdate_update,name='dateupdate'),

####### Payment Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/payment/create/$',views.Payment_createview.as_view(),name='paymentcreate'),

####### Receipt Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/receipt/create/$',views.Receipt_createview.as_view(),name='receiptcreate'),

####### Contra Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/contra/create/$',views.Contra_createview.as_view(),name='contracreate'),

####### Daybook Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/daybook/$',views.DaybookListView.as_view(),name='daybook'),




    url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_condensed_view,name='trialbalcond'),

    url(r'^company/(?P<pk>\d+)/P&L/date/(?P<pk3>\d+)/$',views.profit_and_loss_condensed_view,name='P&Lcond'),

    url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_condensed_view,name='blsht'),


    url(r'^company/(?P<pk>\d+)/cashbankbook/date/(?P<pk3>\d+)/$',views.cash_and_bank_view,name='cash_and_bank'),


]

cfehome/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.conf import settings

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^base/$", views.base.as_view(), name="base"),
    path('admin/', admin.site.urls),
    url(r"^message/", include("messaging.urls", namespace="messaging")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r"^products/", include("ecommerce_integration.urls", namespace="products")),
    url(r"^carts/", include("ecommerce_cart.urls", namespace="carts")),
    url(r"^accounting_double_entry/", include("accounting_double_entry.urls", namespace="accounting_double_entry")),
    url(r"^company/", include("company.urls", namespace="company")),
    url(r"^todo/", include("todogst.urls", namespace="todogst")),
    url(r"^profile/", include("userprofile.urls", namespace="userprofile")),
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r"^pdf/", include("pdf.urls", namespace="pdf")),
    # url(r"^gst/", include("Gst.urls", namespace="gst")),
    url(r'^select2/', include('django_select2.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r"^consultancy/", include("consultancy.urls", namespace="consultancy")),
    url(r"^stockkeeping/", include("stockkeeping.urls", namespace="stockkeeping")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'erpcloud.views.custom_404'
handler500 = 'erpcloud.views.custom_500'

company/urls.py
from django.conf.urls import url,include
from company import views
from django.urls import path

app_name = 'company'

urlpatterns = [
######################### Company Urls ################################################
    url(r'^$',views.companyListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.companyDetailView.as_view(),name='Dashboard'),
    url(r'^create/$',views.companyCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.companyUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<id>\d+)/$',views.company_delete,name='delete'),
	
]

pdf/urls.py
from django.conf.urls import url
from pdf import views

app_name = 'pdf'

urlpatterns = [

########################################### PDF URLS ############################################################################################################################
	url(r'^company/(?P<pk1>\d+)/purchasedetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Purchase_PDF.as_view(),name='purchasedetailpdf'),
	url(r'^company/(?P<pk1>\d+)/saledetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Sales_PDF.as_view(),name='salesdetailpdf'),
    url(r'^company/(?P<pk>\d+)/ledgermonthlypdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Ledger_Monthly_PDF.as_view(),name='ledgerdetailmonthlypdf'),


]

company/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
import datetime

from django.contrib.auth import get_user_model
User = get_user_model()



class company(models.Model):
	User = models.ForeignKey(User,related_name="Company_Owner",on_delete=models.CASCADE,null=True,blank=True)
	counter = models.IntegerField(blank=True,null=True)
	urlhash = models.CharField(max_length=100, null=True, blank=True, unique=True)
	created_date = models.DateField(auto_now_add=True)
	modified_date = models.DateField(auto_now=True)
	Name = models.CharField(max_length=50,blank=False)
	types = (   ('Individual','Individual'),
				('HUF','HUF'),
				('Partnership','Partnership'),
				('Trust','Trust'),
				('Private Company','Private Company'),
				('Public Company','Public Company'),
				('LLP','LLP'),
				#('',''),
			)
	Business_nature_Service_Provider = models.BooleanField(default=False)
	Business_nature_Retail = models.BooleanField(default=False)
	Business_nature_Wholesale = models.BooleanField(default=False)
	Business_nature_Works_Contract  = models.BooleanField(default=False)
	Business_nature_Leasing = models.BooleanField(default=False)
	Business_nature_Factory_Manufacturing = models.BooleanField(default=False)
	Business_nature_Bonded_Warehouse = models.BooleanField(default=False)
	Business_nature_Other = models.BooleanField(default=False)
	Please_specify = models.BooleanField(default=False)
	Type_of_company = models.CharField(max_length=32,choices=types,default='Individual')
	Shared_Users = models.CharField(max_length=32,default="Current User only") # company data sharing
	Address = models.TextField()
	Country = models.CharField(max_length=32,default='India')
	State_Name 		= (
		('Choose','Choose'),
		('Andhra Pradesh','Andhra Pradesh'),
		('Andaman & Nicobar Islands','Andaman & Nicobar Islands'),
		('Arunachal Pradesh','Arunachal Pradesh'),
		('Assam','Assam'),
		('Bihar','Bihar'),
		('Chandigarh','Chandigarh'),
		('Chhattisgarh','Chhattisgarh'),
		('Dadra and Nagar Haveli','Dadra and Nagar Haveli'),
		('Daman and Diu','Daman and Diu'),
		('Delhi','Delhi '),
		('Goa','Goa'),
		('Gujrat','Gujrat'),
		('Haryana','Haryana'),
		('Himachal Pradesh','Himachal Pradesh'),
		('Jammu and Kashmir','Jammu and Kashmir'),
		('Jharkhand','Jharkhand'),
		('Karnataka','Karnataka'),
		('Kerala','Kerala'),
		('Lakshadweep','Lakshadweep'),
		('Madhya Pradesh','Madhya Pradesh'),
		('Maharashtra','Maharashtra'),
		('Manipur','Manipur'),
		('Meghalaya','Meghalaya'),
		('Mizoram','Mizoram'),
		('Nagaland','Nagaland'),
		('Odisha','Odisha'),
		('Puducherry','Puducherry'),
		('Punjab','Punjab'),
		('Rajasthan','Rajasthan'),
		('Sikkim','Sikkim'),
		('Tamil Nadu','Tamil Nadu'),
		('Telangana','Telangana'),
		('Tripura','Tripura'),	
		('Uttar Pradesh','Uttar Pradesh'),
		('Uttarakhand','Uttarakhand'),
		('West Bengal','West Bengal'),
		)   		
	State = models.CharField(max_length=100,choices=State_Name,default='Choose')
	Pincode = models.CharField(max_length=32)
	Telephone_No = models.BigIntegerField(blank=True,null=True)
	Mobile_No = models.BigIntegerField(blank=True,null=True)

	financial_date = (
		(datetime.date((datetime.datetime.now().year),4,1),datetime.date((datetime.datetime.now().year),4,1)),
		(datetime.date((datetime.datetime.now().year),1,1),datetime.date((datetime.datetime.now().year),1,1))
		)


	Financial_Year_From = models.DateField(choices=financial_date,default=datetime.date(int(datetime.datetime.now().year),4,1), blank=False)
	Books_Begining_From = models.DateField(default=datetime.date(2018,4,1), blank=False)
	gst  = models.CharField(max_length=20,blank=True,null=True)
	pan  = models.CharField(max_length=18,blank=True,null=True)


	def __str__(self):
		return self.Name

	def save(self):
		if self.id:
			self.modified_date = datetime.datetime.now()
		else:
			self.created_date = datetime.datetime.now()
		super(company,self).save()

	def save(self, **kwargs):
		super(company, self).save()
		if not self.urlhash:
			if self.User.profile.user_type == 'Bussiness User':
				self.urlhash = 'BU'+ '-' + str(self.User.id) + '-'+ 'P' + '-' + '1' + '-'+ 'C' + str(self.counter) 
				company.objects.filter(pk=self.pk).update(urlhash=self.urlhash)
			else:
				self.urlhash = 'PU'+ '-' + str(self.User.id) + '-'+ 'P' + '-' + '1' + '-'+ 'C' + str(self.counter) 
				company.objects.filter(pk=self.pk).update(urlhash=self.urlhash)

	class Meta:
		ordering = ["Name"]
		



 










# def create_company(sender, **kwargs):
# 	if kwargs['created']:
# 		Company_Name = companyowner.objects.create(Company=kwargs['instance'])


# post_save.connect(create_user, sender=company)

company/forms.py
from django import forms
from company.models import company
from accounting_double_entry.models import selectdatefield



class DateInput(forms.DateInput):
    input_type = 'date'




class companyform(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(companyform, self).__init__(*args, **kwargs)
		self.fields['Name'].widget.attrs = {'class': 'form-control',}
		self.fields['Type_of_company'].widget.attrs = {'class': 'form-control',}
		self.fields['Shared_Users'].widget.attrs = {'class': 'form-control',}
		self.fields['Address'].widget.attrs = {'class': 'form-control',}
		self.fields['Country'].widget.attrs = {'class': 'form-control',}
		self.fields['State'].widget.attrs = {'class': 'form-control',}
		self.fields['Pincode'].widget.attrs = {'class': 'form-control',}
		self.fields['Telephone_No'].widget.attrs = {'class': 'form-control',}
		self.fields['Mobile_No'].widget.attrs = {'class': 'form-control',}
		self.fields['Financial_Year_From'].widget.attrs = {'class': 'form-control select2',}
		self.fields['Books_Begining_From'].widget.attrs = {'class': 'form-control',}
		self.fields['gst'].widget.attrs = {'class': 'form-control',}
		self.fields['pan'].widget.attrs = {'class': 'form-control',}


	class Meta:
		model = company
		fields = ('Name', 'Type_of_company','Business_nature_Service_Provider','Business_nature_Retail','Business_nature_Wholesale','Business_nature_Works_Contract','Business_nature_Leasing','Business_nature_Factory_Manufacturing','Business_nature_Bonded_Warehouse','Business_nature_Other','Please_specify','Shared_Users','Address','Country','State','Pincode','Telephone_No','Mobile_No','Financial_Year_From','Books_Begining_From','gst','pan')
		widgets = {
            'Books_Begining_From': DateInput(),
        }

company/templates/company/Dashboard.html
{% extends "clouderp/base.html" %}
{% load staticfiles %}

{% block title %}Dashboard{% endblock %}


    
			
			
{% block content %}
<div class="content-wrapper">
	<!-- <div class="container"> -->
		<section class="content-header">
			<!-- <div class="col-md-12"> -->
				<h1>
					<strong>Selected Company : {{company_details.Name}}</strong>
				</h1>
        <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Company list</a></li>
        <li class="active">Selected Company</li>
      </ol>
			<!-- </div> -->
		</section>

		<!-- <div class="container">
    		<p><a class='btn btn-warning' >Update</a></p>

  		</div>
  		<br>
  		<div class="container">
    		<p><a class='btn btn-danger' >Delete</a></p>

  		</div> -->
  
      <section class="content">
      <div class="callout callout-info">
        <h4>Welcome!</h4>
        Welcome to predict books your personal AI powered business engine!
        <!-- <a href="http://getbootstrap.com/javascript/#modals">Bootstrap documentation</a> -->
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="box box-default" >
            <!-- <div class="box-header with-border">
              <h3 class="box-title">Modal Examples</h3>
            </div> -->
            <div class="box-body">
              <a href="{% url 'company:list' %}" class="btn btn-success" role="button">Select Company </a>
              <a href="{% url 'company:update' pk=company_details.pk %}" class="btn btn-warning" role="button">Update Company details</a>
            
              
              {% if not selectdatefield_details %}

                  
                     <button class="btn btn-primary show-form pull-right" data-url="{% url 'accounting_double_entry:datecreate' %}">
                      <span class="glyphicon glyphicon-plus"></span>
                        Select Date Range
                      </button>

                {% else %} 
              
  
                            <button  class="btn btn-warning show-form-update pull-right" data-url="{% url 'accounting_double_entry:dateupdate' pk=selectdatefield_details.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                              Update Date Range 
                            </button>

                      <a id="book-table-date" class="pull-right"><strong>Selected Period: From</strong> {{ selectdatefield_details.Start_Date|date }} <strong>To</strong> {{ selectdatefield_details.End_Date|date }}  &nbsp;</a>  

                 

                {% endif %} 
               
              
              
            </div>
          </div>
        </div>
      </div>

      <div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

            <a href="{% url 'accounting_double_entry:list' pk=company_details.pk pk3=selectdatefield_details.pk  %}" class="btn btn-success" role="button">Select Journal </a>
            <a href="{% url 'accounting_double_entry:create' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-warning" role="button">Create Journal</a>

            <div class="pull-right">

              <a href="{% url 'accounting_double_entry:ledgerlist' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-success" role="button">Select Ledger </a>
              <a href="{% url 'accounting_double_entry:ledgercreate' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-warning" role="button">Create Ledger</a>
            
            </div>
             

        
        
        
        </div>
      
      </div>
    
    </div>

</div>


	<!-- here is the personal statistics part		 -->
  <!-- Main row -->
  <style type="text/css">
    #blue {
      color: #3b8bba;
      text-shadow: 1px 1px 1px #ccc;
      font-size: 1.5em;
    }

    #shadow {
      color: #c1c7d1;
      text-shadow: 1px 1px 1px #ccc;
      font-size: 1.5em;
    }

  </style>
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-7 connectedSortable">
          <!-- Custom tabs (Charts with tabs)-->
          <div class="nav-tabs-custom">
            <!-- Tabs within a box -->
            <ul class="nav nav-tabs pull-right">
              <li><i class="fa fa-square" id="shadow" aria-hidden="true"></i>&nbsp; Purchases&nbsp;</li>
              <li><i class="fa fa-square" id="blue" aria-hidden="true"></i>&nbsp; Sales&nbsp;</li>

              <li class="pull-left header"><i class="fa fa-inbox"></i>Purchase and Sales</li>
            </ul>
            <div class="tab-content no-padding">
              <!-- Morris chart - Sales -->
              <!-- <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"></div> -->

              <canvas class="chart tab-pane active" id="areaChart" style="height:250px"></canvas>
              <!-- <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;"></div> -->
            </div>
          </div>
          <!-- /.nav-tabs-custom -->
          <div class="box box-solid bg-teal-gradient">
            <div class="box-header">
              <i class="fa fa-th"></i>

              <h3 class="box-title">Profit Graph</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn bg-teal btn-sm" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn bg-teal btn-sm" data-widget="remove"><i class="fa fa-times"></i>
                </button>
              </div>
            </div>
            <div class="box-body border-radius-none">
              <div class="chart" id="line-chart" style="height: 250px;"></div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer no-border">
              <div class="row">
                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                  <input type="text" class="knob" data-readonly="true" value="20" data-width="60" data-height="60"
                         data-fgColor="#39CCCC">

                  <div class="knob-label">Mail-Orders</div>
                </div>
                <!-- ./col -->
                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                  <input type="text" class="knob" data-readonly="true" value="50" data-width="60" data-height="60"
                         data-fgColor="#39CCCC">

                  <div class="knob-label">Online</div>
                </div>
                <!-- ./col -->
                <div class="col-xs-4 text-center">
                  <input type="text" class="knob" data-readonly="true" value="30" data-width="60" data-height="60"
                         data-fgColor="#39CCCC">

                  <div class="knob-label">In-Store</div>
                </div>
                <!-- ./col -->
              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
         

</section>

      </div>
      <!-- /.row (main row) -->


</section>	


  <div class="modal fade" id="modal-book-date">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>	



{% endblock %}
			
	
	

company/templates/company/companies.html
{% load staticfiles %}
{% load mathfilters %}
{% for company in company_list %}

  {% for selectdatefield in selectdates %}

    <tr>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{company.Name}}</a></td>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{company.Books_Begining_From}}</a></td>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{capital|floatformat:2|abs}}</a></td>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{company.Type_of_company}}</a></td>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{Assets|floatformat:2|abs}}</a></td>
      <td><a href="{% url 'company:Dashboard' pk=company.pk pk3=selectdatefield.pk %}">{{company.modified_date}}</a></td>
      <td>100000</td>
      <td>

      <button class="btn btn-danger show-form-delete" data-url="{% url 'company:delete' company.id %}">
          <span class="glyphicon glyphicon-trash"></span>
                                

      </button>
      </td>
      <td><a href="#" class="btn btn-default"><i class="fa fa-gear"></i></a></td>
      
    </tr>

  {% endfor %}  
                    
{% endfor %}

company/templates/company/company_confirm_delete.html
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'company:delete' Company.id %}" class="delete-form">
	{% csrf_token %}
		<div class="modal-header">
		<h5 class="modal-title" >Delete Company</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
		</div>
		<div class="modal-body">
		<p class="lead"> Are you sure you want to delete this company <strong>{{Company.Name}}</strong></p>
		</div>
		<div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		<input type="submit" id="reload_answer" class="btn btn-danger" value="Delete Company">
		</div>
</form>


<script type="text/javascript">
$('#reload_answer').click(function() {
    location.reload();
});
</script>

company/templates/company/company_list_2.html
                    {% for selectdatefield_details in selectdates %}

                            <button class="btn btn-warning show-form-update pull-right" data-url="{% url 'accounting_double_entry:dateupdate' pk=selectdatefield_details.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                              Update Date Range 
                            </button>

                      <a class="pull-right"><strong>Selected Period: From</strong> {{ selectdatefield_details.Start_Date|date }} <strong>To</strong> {{ selectdatefield_details.End_Date|date }}  &nbsp;</a> 

                    {% endfor %} 