accounting_double_entry/urls.py
from django.conf.urls import url
from accounting_double_entry import views

app_name = 'accounting_double_entry'

urlpatterns = [

####### Groups Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/grouplist/$',views.group1ListView.as_view(),name='grouplist'),    
    url(r'^company/(?P<pk1>\d+)/groupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1DetailView.as_view(),name='groupdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupcreate/$',views.group1CreateView.as_view(),name='groupcreate'),
    url(r'^company/(?P<pk1>\d+)/groupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group1UpdateView.as_view(),name='groupupdate'),
    url(r'^company/(?P<pk>\d+)/groupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.group_delete_view,name='groupdelete'),

####### Group Summary Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/groupsummary/$',views.groupsummaryListView.as_view(),name='groupsummary'),    
    url(r'^company/(?P<pk>\d+)/groupdetailsummary/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.groupsummary_detail_view,name='groupdetailsummary'),


####### Ledger Monthly Url ########################################

    url(r'^company/(?P<pk>\d+)/ledgermonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger_monthly_detail_view,name='ledgerdetailmonthly'),

####### Ledger Urls ########################################


    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerlist/$',views.ledger1ListView.as_view(),name='ledgerlist'),
    url(r'^company/(?P<pk>\d+)/ledgerdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.ledger1_detail_view,name='ledgerdetail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgercreate/$',views.ledger1CreateView.as_view(),name='ledgercreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerupdate/(?P<pk2>\d+)/$',views.ledger1UpdateView.as_view(),name='ledgerupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/ledgerdelete/(?P<pk2>\d+)/$',views.ledger_delete_view,name='ledgerdelete'),

####### Journal Register Urls ########################################  

     url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journalregister/$',views.Journal_Register_view.as_view(),name='journalregister'),

####### Journal Urls ########################################  

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journallist/$',views.journalListView.as_view(),name='list'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journallist/(?P<pk2>\d+)/$',views.journal_detail,name='detail'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/create/$',views.journalCreateView.as_view(),name='create'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/journal/update/(?P<pk2>\d+)/$',views.journalUpdateView.as_view(),name='update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/journal/delete/(?P<pk2>\d+)/$',views.journal_delete_view,name='delete'),


####### PL JOURNAL Urls ######################################## 

    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journallist/(?P<pk2>\d+)/$',views.pl_journal_detail,name='pl_detail'),
    url(r'^company/(?P<pk1>\d+)/date/(?P<pk3>\d+)/pl_journal/update/(?P<pk2>\d+)/$',views.pl_journalUpdateView.as_view(),name='pl_update'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/pl_journal/delete/(?P<pk2>\d+)/$',views.pl_journal_delete_view,name='pl_delete'),

####### Multijournal Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/$',views.Multijournal_listview.as_view(),name='multijournallist'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournallist/(?P<pk2>\d+)/$',views.multijournal_detail,name='multijournaldetail'),   
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/create/$',views.Multijournal_createview.as_view(),name='multijournalcreate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournalupdate/(?P<pk2>\d+)/$',views.Multijournal_updateview.as_view(),name='multijournalupdate'),
    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/multijournal/delete/(?P<pk2>\d+)/$',views.multijournal_deleteview.as_view(),name='multijournaldelete'),


####### Daterange Urls ########################################  
  
    url(r'^daterangecreate/$',views.selectdate_create,name='datecreate'),
    url(r'^daterangeupdate/(?P<pk>\d+)/$',views.selectdate_update,name='dateupdate'),

####### Payment Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/payment/create/$',views.Payment_createview.as_view(),name='paymentcreate'),

####### Receipt Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/receipt/create/$',views.Receipt_createview.as_view(),name='receiptcreate'),

####### Contra Urls ######################################## 

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/contra/create/$',views.Contra_createview.as_view(),name='contracreate'),

####### Daybook Urls ########################################

    url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/daybook/$',views.DaybookListView.as_view(),name='daybook'),




    url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_condensed_view,name='trialbalcond'),

    url(r'^company/(?P<pk>\d+)/P&L/date/(?P<pk3>\d+)/$',views.profit_and_loss_condensed_view,name='P&Lcond'),

    url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_condensed_view,name='blsht'),


    url(r'^company/(?P<pk>\d+)/cashbankbook/date/(?P<pk3>\d+)/$',views.cash_and_bank_view,name='cash_and_bank'),


]

company/urls.py
from django.conf.urls import url,include
from company import views
from django.urls import path

app_name = 'company'

urlpatterns = [
######################### Company Urls ################################################
    url(r'^$',views.companyListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.companyDetailView.as_view(),name='Dashboard'),
    url(r'^create/$',views.companyCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.companyUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<id>\d+)/$',views.company_delete,name='delete'),
	
]

pdf/urls.py
from django.conf.urls import url
from pdf import views

app_name = 'pdf'

urlpatterns = [

########################################### PDF URLS ############################################################################################################################
	url(r'^company/(?P<pk1>\d+)/purchasedetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Purchase_PDF.as_view(),name='purchasedetailpdf'),
	url(r'^company/(?P<pk1>\d+)/saledetailpdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Sales_PDF.as_view(),name='salesdetailpdf'),
    url(r'^company/(?P<pk>\d+)/ledgermonthlypdf/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Generate_Ledger_Monthly_PDF.as_view(),name='ledgerdetailmonthlypdf'),


]

stockkeeping/urls.py
from django.conf.urls import url
from stockkeeping import views

app_name = 'stockkeeping'

urlpatterns = [


################################### Simple Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitlist$',views.Simpleunits_listview.as_view(),name='simplelist'),
	url(r'^company/(?P<pk1>\d+)/simpleunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_detailsview.as_view(),name='simpledetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/simpleunitcreate/$',views.Simpleunits_createview.as_view(),name='simplecreate'),
	url(r'^company/(?P<pk1>\d+)/simpleunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_updateview.as_view(),name='simpleupdate'),
	url(r'^company/(?P<pk>\d+)/simpleunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Simpleunits_deleteview.as_view(),name='simpledelete'),

################################### Compound Units Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitlist$',views.Compoundunit_listview.as_view(),name='compoundlist'),
	url(r'^company/(?P<pk1>\d+)/compoundunitdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_detailsview.as_view(),name='compounddetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/compoundunitcreate/$',views.Compoundunits_createview.as_view(),name='compoundcreate'),
	url(r'^company/(?P<pk1>\d+)/compoundunitupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_updateview.as_view(),name='compoundupdate'),
	url(r'^company/(?P<pk>\d+)/compoundunitdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Compoundunits_deleteview.as_view(),name='compounddelete'),

################################### Stockgroup Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgrouplist$',views.Stockgroup_listview.as_view(),name='stockgrouplist'),
	url(r'^company/(?P<pk1>\d+)/stockgroupdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_detailsview.as_view(),name='stockgroupdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockgroupcreate/$',views.Stockgroup_createview.as_view(),name='stockgroupcreate'),
	url(r'^company/(?P<pk1>\d+)/stockgroupupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_updateview.as_view(),name='stockgroupupdate'),
	url(r'^company/(?P<pk>\d+)/stockgroupdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockgroup_deleteview.as_view(),name='stockgroupdelete'),


################################### Stockdata Monthly Url ######################################

    url(r'^company/(?P<pk>\d+)/stockmonthly/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockitems_Monthly_view,name='stockmonthly'),


################################### Stockdata Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdata$',views.Stockdata_listview.as_view(),name='stockdatalist'),
	url(r'^company/(?P<pk1>\d+)/stockdatadetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_detailsview.as_view(),name='stockdatadetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stockdatacreate/$',views.Stockdata_createview.as_view(),name='stockdatacreate'),
	url(r'^company/(?P<pk1>\d+)/stockdataupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_updateview.as_view(),name='stockdataupdate'),
	url(r'^company/(?P<pk>\d+)/stockdatadelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Stockdata_deleteview.as_view(),name='stockdatadelete'),

################################### Purchase Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchase$',views.Purchase_listview.as_view(),name='purchaselist'),
	url(r'^company/(?P<pk1>\d+)/purchasedetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_detailsview.as_view(),name='purchasedetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/purchasecreate/$',views.Purchase_createview.as_view(),name='purchasecreate'),
	url(r'^company/(?P<pk1>\d+)/purchaseupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_updateview.as_view(),name='purchaseupdate'),
	url(r'^company/(?P<pk>\d+)/purchasedelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Purchase_deleteview.as_view(),name='purchasedelete'),


################################### Purchase Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Purchase_Register/date/(?P<pk3>\d+)/$',views.Purchase_Register_view.as_view(),name='purchase_register'),



################################### Sale Register Url #######################################

	url(r'^company/(?P<pk>\d+)/Sale_Register/date/(?P<pk3>\d+)/$',views.Sales_Register_view.as_view(),name='sale_register'),

################################### Sales Url #######################################

	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/sales$',views.Sales_listview.as_view(),name='saleslist'),
	url(r'^company/(?P<pk1>\d+)/salesdetail/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_detailsview.as_view(),name='salesdetail'),
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/salescreate/$',views.Sales_createview.as_view(),name='salescreate'),
	url(r'^company/(?P<pk1>\d+)/salesupdate/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_updateview.as_view(),name='salesupdate'),
	url(r'^company/(?P<pk>\d+)/salesdelete/(?P<pk2>\d+)/date/(?P<pk3>\d+)/$',views.Sales_deleteview.as_view(),name='salesdelete'),


	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/stcreate/$',views.Stock_Total_createview.as_view(),name='stocktotalcreate'),


################################### Closing Stock Url #######################################
	
	url(r'^company/(?P<pk>\d+)/date/(?P<pk3>\d+)/$',views.closing_list_view.as_view(),name='closingstock'),


################################### Profit & Loss Url #######################################

    url(r'^company/(?P<pk>\d+)/Profitloss/date/(?P<pk3>\d+)/$',views.profit_and_loss_view,name='profitloss'),

################################### Trial Balance Url #######################################

	url(r'^company/(?P<pk>\d+)/trialbalance/date/(?P<pk3>\d+)/$',views.trial_balance_view,name='trialbal'),

################################### Balance Sheet Url #######################################

	
	url(r'^company/(?P<pk>\d+)/balancesheet/date/(?P<pk3>\d+)/$',views.balance_sheet_view,name='balsht'),

]

stockkeeping/templates/stockkeeping/closing_stock.html
{% extends "clouderp/base.html" %}
{% load staticfiles %}
{% load mathfilters %}

{% block title %}StockItem Details{% endblock %}




{% block content %}

<div class="content-wrapper">
	 <section class="content-header">
        <!-- <div class="col-md-12 col-md-offset-4"> -->
          <h1>
            <strong>Company : {{company_details.Name}}</strong>
          </h1>
                <ol class="breadcrumb">
                       <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                       <!-- <li><a href="#">Company list</a></li> -->
                     <li class="">Company list</li>
                     <li class="active">Group Details</li>
            </ol>
           
        <!-- </div> -->
      </section>

  <section class="content">
      <div class="callout callout-warning">
        <h4>Welcome!</h4>
        Welcome to predict books your personal AI powered business engine!
        <!-- <a href="http://getbootstrap.com/javascript/#modals">Bootstrap documentation</a> -->
      </div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

      <a href="{% url 'company:list' %}" class="btn btn-success" role="button">Select Company </a>
              <a href="{% url 'company:create' %}" class="btn btn-warning" role="button">Create Company details</a>
              

        
        
              {% if not selectdatefield_details %}

                  
                     <button class="btn btn-primary show-form pull-right" data-url="{% url 'accounting_double_entry:datecreate' %}">
                      <span class="glyphicon glyphicon-plus"></span>
                        Select Date Range
                      </button>

                {% else %} 
              
  
                            <button  class="btn btn-warning show-form-update pull-right" data-url="{% url 'accounting_double_entry:dateupdate' pk=selectdatefield_details.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                              Update Date Range 
                            </button>

                      <a id="book-table-date" class="pull-right"><strong>Selected Period: From</strong> {{ selectdatefield_details.Start_Date|date }} <strong>To</strong> {{ selectdatefield_details.End_Date|date }}  &nbsp;</a>  

                 

                {% endif %}
        
        </div>
      
      </div>
    
    </div>

</div>

<div class="row">
      <div class="col-xs-12">
          <div class="box box-default">
          <div class="box-body">

          <a href="{% url 'stockkeeping:stockdatalist' pk=company_details.pk pk3=selectdatefield_details.pk %}" class="btn btn-success" role="button">Select Stockitem</a>
          
          <a href="{% url 'stockkeeping:stockdatacreate' pk=company_details.pk pk3=selectdatefield_details.pk  %}" class="btn btn-warning" role="button">Create Stockitem</a>

            <button type="button" class="btn btn-default dropdown-toggle pull-right" data-toggle="dropdown">Wt AVG(default)
                    <span class="fa fa-caret-down"></span></button>
                  <ul class="dropdown-menu pull-right">
                    <li><a  href="{% url 'stockkeeping:closingstock' pk=company_details.pk pk3=selectdatefield_details.pk %}">Wt AVG</a></li>
                    <li><a  href="">LIFO</a></li>
                    <li><a href="">FIFO</a></li>
                    
                                        
                  </ul>

                <a class="pull-right"><strong>Stock valuation Method :</strong>&nbsp;</a>

        
        
        </div>
      
      </div>
    
    </div>

</div>

		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="box box-info">

<div id="printableArea">


  <!--         CSS for not printing the urls in print preview
 -->      <style>
          @media print  
          {
          a[href]:after {
          content: none !important;
           }
          @page {
          margin-top: 0;
          margin-bottom: 0;
          }
           body{
          padding-top: 72px;
          padding-bottom: 72px ;
          }
          }
          </style>
  
  <div class="box-header with-border">
              
              <h2 class="box-title"><b>Stock Item Summary</b></h2>
        
          </div>

          <div class="box-body table-responsive no-padding">

        <style type="text/css">

          .table-bordered td, .table-bordered th{
            border-color: #bfbfbf !important;
                    
               }
        </style>

          <table class="table table-bordered table-striped">
              <tr>
                <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></th>
                <th class="col-lg-9 col-md-9 col-sm-9 col-xs-9"><center>Closing Balance</center></th>

              </tr>
          </table>

            <table class="table table-bordered table-striped">

              <thead>
              <tr>
               <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><center>Particulars</center></th>
                <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Total Quantity</th>
                <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Avg Rate</th>
                <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Value(&#8377)</th>
                  
              </tr>
              </thead>
             

          <tbody>
            {% for stockdata in Totalquantity %}
              <tr>

                <th><a href="{% url 'stockkeeping:stockmonthly' pk=company_details.pk pk2=stockdata.id pk3=selectdatefield_details.pk %}">{{stockdata.stock_name}}</a></th>
                
                <td>{{ stockdata.difference|floatformat:0|abs }}</td>

                <td>{{ stockdata.total|div:stockdata.difference|floatformat:2|abs }}</td>
                <td>{{ stockdata.total|floatformat:2|abs }}</td>
              </tr>

            {% endfor %}
            
          </tbody>
            
            </table>
          </div>

</div>
					

                            <div class="box-footer">
                    
                    <div class="pull-left">
                    <p>Showing item {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} entries</p>

                    <br>

                    <input class='btn btn-default' type="button" onclick="printDiv('printableArea')" value="Print" />
                  </div>

                  <div class="pull-right">
                        {% if is_paginated %}
                            <ul class="pagination">
                             {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                              {% else %}
                                <li class="disabled"><span>Previous</span></li>
                              {% endif %}
                              {% for i in paginator.page_range %}
                                  {% if page_obj.number == i %}
                                     <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                  {% else %}
                                      <li><a href="?page={{ i }}">{{ i }}</a></li>
                                  {% endif %}
                              {% endfor %}
                              {% if page_obj.has_next %}
                                  <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                              {% else %}
                                  <li class="disabled"><span>Next</span></li>
                              {% endif %}
                          </ul>
                      {% endif %}
                    </div>
                  </div>

				</div>


				</div>
			</div>
		
	</section>
</div>

  <div class="modal fade" id="modal-book-date">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>


<script type="text/javascript">
  
  function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;

     window.print();

     document.body.innerHTML = originalContents;
  }
</script> 

{% endblock %}